# These are supported funding model platforms

github: [oliverrdz] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: [https://www.paypal.com/donate/?business=7DE8F259LFTQJ&no_recurring=0&item_name=Thank+you+for+your+donation%21+This+will+help+me+continue+maintaining+Soft+Potato+and+keeping+it+free%21&currency_code=USD] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
