# These are supported funding model platforms

github: [oliverrdz]
custom: https://www.paypal.com/donate/?business=7DE8F259LFTQJ&no_recurring=0&item_name=Thank+you+for+your+donation%21+This+will+help+me+continue+maintaining+Soft+Potato+and+keeping+it+free%21&currency_code=USD
